---
- name: "update apt"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: "Remove some dependences that are not required"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "Install Node.js and NPM"
  apt:
    name:
      - "nodejs"
      - "npm"
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest